anguage: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm i  
  - npm test
  - npm run build 
deploy:
  provider: surge
  skip_cleanup: true
  domain: jotto-wendy.surge.sh
  project: ./build/
  on:
    branch: master